name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deno Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: a632079-clash-rulesets
          entrypoint: jsr:@std/http/file-server
