name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deno Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: clash-nyanpasu-manifest
          entrypoint: jsr:@std/http/file-server
          root: .
